image: maven:3.6.3-jdk-8

definitions:
  # Used for accessing packages.atlassian.com
  # https://hello.atlassian.net/wiki/spaces/RELENG/pages/515270561
  artifactory-access:
    - &artifactory-prepare
      pipe: docker://atlassian/artifactory-sidekick:latest
    - &artifactory-enable
        source .artifactory/activate.sh

pipelines:
  default:
    - step: &test
        name: Build and test
        caches:
          - maven
        script:
          - *artifactory-prepare
          - *artifactory-enable
          - mvn verify
  branches:
    main:
      - step: *test
      - step:
          name: Release version
          trigger: manual
          caches:
            - maven
          script:
            - *artifactory-prepare
            - *artifactory-enable
            - BASE_VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -q -DforceStdout`
            - VERSION=${BASE_VERSION}.${BITBUCKET_BUILD_NUMBER}
            - mvn versions:set -DnewVersion=${VERSION}
            - mvn deploy -Darguments=-DskipTests
            - git tag -a ${VERSION} -m "Kotlin JQL v"${VERSION}
            - git push --follow-tags
