image: maven:3.6.3-jdk-8

definitions:
  # Used for accessing packages.atlassian.com
  # https://hello.atlassian.net/wiki/spaces/RELENG/pages/515270561
  artifactory-access:
    - &artifactory-prepare
      pipe: docker://atlassian/artifactory-sidekick:latest
    - &artifactory-enable
        source .artifactory/activate.sh

pipelines:
  default:
    - step: &test
        name: Build and test
        caches:
          - maven
        script:
          - *artifactory-prepare
          - *artifactory-enable
          - mvn verify
  branches:
    main:
      - step: *test
      - step:
          name: Release version
          trigger: manual
          caches:
            - maven
          script:
            - *artifactory-prepare
            - *artifactory-enable
            - mvn -B release:prepare release:perform -Darguments=-DskipTests -DscmCommentPrefix="[skip ci]"
